SELECT
    DATE_TRUNC('month', CLAIM_DATE) AS CLAIM_MONTH,
    PROVIDER_ID,

    COUNT(*) AS TOTAL_CLAIMS,
    SUM(CLAIM_AMOUNT) AS TOTAL_BILLED,
    SUM(PAID_AMOUNT) AS TOTAL_PAID,
    SUM(DENIED_AMOUNT) AS TOTAL_DENIED,

    -- KPI
    SUM(DENIED_AMOUNT) / NULLIF(SUM(CLAIM_AMOUNT), 0) AS DENIAL_RATE

FROM {{ ref('fact_claims') }}
GROUP BY 1, 2