name: dbtdemo5
version: 1.0.0
config-version: 2
profile: dbtdemo5
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  snowflake_dbt_demo5:
    silver:
      +materialized: view
    gold:
      +materialized: table
