dbtdemo5:
  target: dev
  outputs:
    YONG:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_DEMO5
      schema: YONG
      threads: 8
    JANE:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_DEMO5
      schema: JANE
      threads: 8
    JOHN:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_DEMO5
      schema: JOHN
      threads: 8
